In [1]:
# Import Dependencies
import pandas as pd
import numpy as np

In [2]:
# Create reference to CSV file
csv_path = "Resources/Soccer2018Data.csv"

# Import the CSV into a pandas DataFrame
soccer_2018_df = pd.read_csv(csv_path, low_memory=False)
soccer_2018_df.head(20)

,Name,Age,Nationality,Overall,Potential,Club,Preferred Position,CAM,CB,CDM,...,RB,RCB,RCM,RDM,RF,RM,RS,RW,RWB,ST
0,Cristiano Ronaldo,32,Portugal,94,94,Real Madrid CF,ST,89.0,53.0,62.0,...,61.0,53.0,82.0,62.0,91.0,89.0,92.0,91.0,66.0,92.0
1,L. Messi,30,Argentina,93,93,FC Barcelona,RW,92.0,45.0,59.0,...,57.0,45.0,84.0,59.0,92.0,90.0,88.0,91.0,62.0,88.0
2,Neymar,25,Brazil,92,94,Paris Saint-Germain,LW,88.0,46.0,59.0,...,59.0,46.0,79.0,59.0,88.0,87.0,84.0,89.0,64.0,84.0
3,L. Suárez,30,Uruguay,92,92,FC Barcelona,ST,87.0,58.0,65.0,...,64.0,58.0,80.0,65.0,88.0,85.0,88.0,87.0,68.0,88.0
4,M. Neuer,31,Germany,92,92,FC Bayern Munich,GK,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,R. Lewandowski,28,Poland,91,91,FC Bayern Munich,ST,84.0,57.0,62.0,...,58.0,57.0,78.0,62.0,87.0,82.0,88.0,84.0,61.0,88.0
6,De Gea,26,Spain,90,92,Manchester United,GK,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,E. Hazard,26,Belgium,90,91,Chelsea,LW,88.0,47.0,61.0,...,59.0,47.0,81.0,61.0,87.0,87.0,82.0,88.0,64.0,82.0
8,T. Kroos,27,Germany,90,90,Real Madrid CF,CDM,83.0,72.0,82.0,...,76.0,72.0,87.0,82.0,81.0,81.0,77.0,80.0,78.0,77.0
9,G. Higuaín,29,Argentina,90,90,Juventus,ST,81.0,46.0,52.0,...,51.0,46.0,71.0,52.0,84.0,79.0,87.0,82.0,55.0,87.0
10,Sergio Ramos,31,Spain,90,90,Real Madrid CF,CB,70.0,87.0,83.0,...,84.0,87.0,74.0,83.0,70.0,71.0,72.0,69.0,81.0,72.0
11,K. De Bruyne,26,Belgium,89,92,Manchester City,RM,86.0,57.0,70.0,...,66.0,57.0,84.0,70.0,85.0,85.0,81.0,85.0,71.0,81.0
12,T. Courtois,25,Belgium,89,92,Chelsea,GK,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
13,A. Sánchez,28,Chile,89,89,Arsenal,RM,85.0,56.0,64.0,...,62.0,56.0,79.0,64.0,85.0,85.0,83.0,86.0,66.0,83.0
14,L. Modrić,31,Croatia,89,89,Real Madrid CF,CDM,86.0,72.0,80.0,...,78.0,72.0,86.0,80.0,83.0,84.0,76.0,83.0,80.0,76.0
15,G. Bale,27,Wales,89,89,Real Madrid CF,RW,86.0,67.0,71.0,...,72.0,67.0,81.0,71.0,87.0,87.0,87.0,87.0,74.0,87.0
16,S. Agüero,29,Argentina,89,89,Manchester City,ST,85.0,44.0,54.0,...,52.0,44.0,75.0,54.0,87.0,84.0,86.0,86.0,57.0,86.0
17,G. Chiellini,32,Italy,89,89,Juventus,CB,55.0,86.0,76.0,...,78.0,86.0,60.0,76.0,55.0,58.0,59.0,56.0,75.0,59.0
18,G. Buffon,39,Italy,89,89,Juventus,GK,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
19,P. Dybala,23,Argentina,88,93,Juventus,ST,86.0,43.0,55.0,...,55.0,43.0,78.0,55.0,86.0,86.0,83.0,87.0,60.0,83.0

In [3]:
# Collect a list of all the unique values in "Preferred Position"

soccer_2018_df["Preferred Position"].unique()
#print(Preferred_position)

#unique_pcat = purchase_df["purchase_category"].unique()
#print(unique_pcat)

array(['ST', 'RW', 'LW', 'GK', 'CDM', 'CB', 'RM', 'CM', 'LM', 'LB', 'CAM',
       'RB', 'CF', 'RWB', 'LWB'], dtype=object)

In [4]:
# Looking only at strikers (ST) to start
ST_soccer_2018_df = soccer_2018_df.loc[soccer_2018_df['Preferred Position']=='ST',:]
ST_soccer_2018_df.head(10)

,Name,Age,Nationality,Overall,Potential,Club,Preferred Position,CAM,CB,CDM,...,RB,RCB,RCM,RDM,RF,RM,RS,RW,RWB,ST
0,Cristiano Ronaldo,32,Portugal,94,94,Real Madrid CF,ST,89.0,53.0,62.0,...,61.0,53.0,82.0,62.0,91.0,89.0,92.0,91.0,66.0,92.0
3,L. Suárez,30,Uruguay,92,92,FC Barcelona,ST,87.0,58.0,65.0,...,64.0,58.0,80.0,65.0,88.0,85.0,88.0,87.0,68.0,88.0
5,R. Lewandowski,28,Poland,91,91,FC Bayern Munich,ST,84.0,57.0,62.0,...,58.0,57.0,78.0,62.0,87.0,82.0,88.0,84.0,61.0,88.0
9,G. Higuaín,29,Argentina,90,90,Juventus,ST,81.0,46.0,52.0,...,51.0,46.0,71.0,52.0,84.0,79.0,87.0,82.0,55.0,87.0
16,S. Agüero,29,Argentina,89,89,Manchester City,ST,85.0,44.0,54.0,...,52.0,44.0,75.0,54.0,87.0,84.0,86.0,86.0,57.0,86.0
19,P. Dybala,23,Argentina,88,93,Juventus,ST,86.0,43.0,55.0,...,55.0,43.0,78.0,55.0,86.0,86.0,83.0,87.0,60.0,83.0
23,P. Aubameyang,28,Gabon,88,88,Borussia Dortmund,ST,82.0,52.0,59.0,...,62.0,52.0,74.0,59.0,84.0,83.0,85.0,84.0,65.0,85.0
31,Z. Ibrahimović,35,Sweden,88,88,Manchester United,ST,83.0,52.0,60.0,...,54.0,52.0,78.0,60.0,83.0,80.0,84.0,82.0,58.0,84.0
38,E. Cavani,30,Uruguay,87,87,Paris Saint-Germain,ST,80.0,58.0,62.0,...,61.0,58.0,74.0,62.0,82.0,79.0,84.0,80.0,64.0,84.0
46,H. Kane,23,England,86,90,Tottenham Hotspur,ST,79.0,57.0,62.0,...,60.0,57.0,74.0,62.0,82.0,78.0,84.0,79.0,62.0,84.0

In [10]:
# Sort the DataFrame by the values in the "ST" column to find the worst
ST_df = ST_soccer_2018_df.sort_values("ST")


# Reset the index so that the index is now based on the sorting locations

ST_df.set_index('ST')

,Name,Age,Nationality,Overall,Potential,Club,Preferred Position,CAM,CB,CDM,...,RAM,RB,RCB,RCM,RDM,RF,RM,RS,RW,RWB
ST,,,,,,,,,,,,,,,,,,,,,
31.0,L. Sackey,18,Ghana,46,64,Scunthorpe United,ST,29.0,45.0,38.0,...,29.0,40.0,45.0,30.0,38.0,29.0,30.0,31.0,29.0,38.0
43.0,M. Zettl,18,Germany,50,67,SpVgg Unterhaching,ST,47.0,32.0,36.0,...,47.0,39.0,32.0,42.0,36.0,46.0,49.0,43.0,49.0,41.0
44.0,O. Sowunmi,21,England,59,71,Yeovil Town,ST,35.0,58.0,47.0,...,35.0,52.0,58.0,37.0,47.0,38.0,38.0,44.0,37.0,49.0
45.0,E. Mason-Clark,17,England,50,63,Barnet,ST,49.0,33.0,35.0,...,49.0,39.0,33.0,42.0,35.0,49.0,50.0,45.0,51.0,40.0
45.0,J. Young,17,Scotland,46,61,Swindon Town,ST,44.0,28.0,29.0,...,44.0,31.0,28.0,38.0,29.0,45.0,42.0,45.0,44.0,32.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
86.0,S. Agüero,29,Argentina,89,89,Manchester City,ST,85.0,44.0,54.0,...,85.0,52.0,44.0,75.0,54.0,87.0,84.0,86.0,86.0,57.0
87.0,G. Higuaín,29,Argentina,90,90,Juventus,ST,81.0,46.0,52.0,...,81.0,51.0,46.0,71.0,52.0,84.0,79.0,87.0,82.0,55.0
88.0,R. Lewandowski,28,Poland,91,91,FC Bayern Munich,ST,84.0,57.0,62.0,...,84.0,58.0,57.0,78.0,62.0,87.0,82.0,88.0,84.0,61.0
88.0,L. Suárez,30,Uruguay,92,92,FC Barcelona,ST,87.0,58.0,65.0,...,87.0,64.0,58.0,80.0,65.0,88.0,85.0,88.0,87.0,68.0
92.0,Cristiano Ronaldo,32,Portugal,94,94,Real Madrid CF,ST,89.0,53.0,62.0,...,89.0,61.0,53.0,82.0,62.0,91.0,89.0,92.0,91.0,66.0

In [30]:
# Save all of the information collected on the worst striker

In [19]:
ST_df.iloc[0, : ]

Name                          L. Sackey
Age                                  18
Nationality                       Ghana
Overall                              46
Potential                            64
Club                  Scunthorpe United
Preferred Position                   ST
CAM                                  29
CB                                   45
CDM                                  38
CF                                   29
CM                                   30
LAM                                  29
LB                                   40
LCB                                  45
LCM                                  30
LDM                                  38
LF                                   29
LM                                   30
LS                                   31
LW                                   29
LWB                                  38
RAM                                  29
RB                                   40
RCB                                  45
RCM                                  30
RDM                                  38
RF                                   29
RM                                   30
RS                                   31
RW                                   29
RWB                                  38
ST                                   31
Name: 17980, dtype: object